minio/Caddyfile, minio/README.md
Additions:
1. Created directory minio
2. Added ``README.md`` and  ``Caddyfile``
=> Instructions for using Caddy as proxy server with Minio.

systemd/README.md
=> Let's make the right assumptions

minio/README.md
@koolhead17, care to give this the thumbs up?
=> Caddy 0.9 is needed for transparent

systemd/caddy.service
caddy 0.9 suggests 8192 is optimal :)
=> Update LimitNOFILE value

laravel/Caddyfile
=> Added Laravel example

isso/README.md
tested with Caddy 0.9.0 and Isso 0.9.10
=> add Isso config example

httpsproxy/caddyfile, httpsproxy/readme.md
I've made the changes you requested.
=> Simply HTTPS Proxy Example with Updates

lumen/caddyfile, lumen/readme.md
Earlier submitted Lumen Caddyfile was not complete and would not run some Lumen sites.
=> Updated Lumen Caddyfile to only redirect if files dont exist

owncloud/Caddyfile, owncloud/readme.md
The config is simply the config from the [caddy blog post](https://caddyserver.com/blog/caddy_and_owncloud) with small tweaks.
I was surprised it was missing from this repo so I just added it. 
I hope you don't mind. :)
=> adds an exmaple config for OwnCloud

grav/Caddyfile, grav/readme.md
This simply adds an example for the Grav CMS.
https://getgrav.org/
=> Adds an example config for Grav

grav/Caddyfile
As mentioned in [a forum thread](https://forum.caddyserver.com/t/grav-feed-problem/961/6) this fixes the RSS issue.
=> Fixes RSS problem

cmsmadesimple/Caddyfile, cmsmadesimple/README.md, cmsmadesimple/caddy@.service
=> Add example: CMS Made Simple

concrete5/Caddyfile, concrete5/README.md, concrete5/caddy@.service
=> Add example: Concrete5

gitea/Caddyfile, gitea/README.md
as title. https://github.com/go-gitea/gitea
website: https://gitea.io
=> Add Gitea caddy example.

drone/Caddyfile, drone/README.md
https://github.com/drone/drone
=> feat: add example configuration with drone.

dokuwiki/Caddyfile_root, dokuwiki/Caddyfile_subdir
and change the `fastcgi` directive order
=> add index in fastcgi directive for dokuwiki

pasthis/Caddyfile, pasthis/README.md
Add [Pasthis](https://github.com/moulecorp/pasthis) configuration snippet.
=> Add Caddy snippet for Pasthis

shopware/Caddyfile
Hey, it's me again. I've tested the configuration a little bit further and faced some issues.
I've spent some time to add all necessary directives for a completely running shop.
In addition, I've created a repo for this configuration only at [janbuecker/shopware-with-caddy](https://github.com/janbuecker/shopware-with-caddy). I'll try to keep it up to date with this repository. :)
Sadly there is no caching control available in caddy, yet. 😞
=> Complete shopware configuration

discourse/Caddyfile
fixed invalid timeout value #73
=> Update Caddyfile fixed invalid timeout value #73

friendica/Caddyfile, friendica/README.md
Example for Friendica social network.
=> Friendica example.

minio/README.md
ironic commit message not intended
=> Spelling fix for minio readme

gnusocial/Caddyfile, gnusocial/README.md
This is a working Caddyfile for GNU Social. It includes README.md with basic info.
=> Added Caddyfile for a GNU Social installation.

drupal/Caddyfile
More comments and standard file-name for easier quick-start.
=> Drupal: Clarification

jira/Caddyfile, jira/Readme.md
I've added Jira as it works in my Configuration (without logging)
=> added Jira

flask/Caddyfile, flask/README.md
Same as Django but as I came here looking for Flask, hopefully this may help.
=> Add Flask example Caddyfile

chevereto/Caddyfile, chevereto/README.md
Added chevereto, used nginx Config and translated it according to https://chevereto.com/docs/requirements
=> Added Chevereto

winphp/Caddyfile
Update example to reflect syntax changes to events
=> Update winphp Example

dokuwiki/Caddyfile_root, dokuwiki/Caddyfile_subdir
The latest version of Dokuwiki does not work with the current config. This pull request resolves issues initially discussed in #45
=> Fixed Dokuwiki Rewrites

youtrack/Caddyfile, youtrack/README.md
https://www.jetbrains.com/youtrack/
=> Add JetBrains YouTrack example

discourse/README.md
=> correct some description

directus/Caddyfile, directus/README.md
Heya! Directus core contributor here. I've updated the Directus example to make it work flawlessly with the latest version of the platform. Thanks!
=> Update Directus example

nextcloud/caddy-reverseproxy-nginx-backend-nextcloud/Caddyfile, nextcloud/caddy-reverseproxy-nginx-backend-nextcloud/README.MD, nextcloud/caddy-reverseproxy-nginx-backend-nextcloud/nginx.conf
Adding config snippets for caddy (and nginx), where Caddy proxies requests for nextcloud to nginx transparently.
=> Nextcloud - Adding config snippets for caddy as reverse proxy and nginx as backend

winphp/Caddyfile, winphp/php_cgi.bat, winphp/php_cgi2.bat, winphp/readme.md
=> Enhance docs for winphp example

picocms/Caddyfile, picocms/README.md
=> Adding PicoCMS PHP-FPM example

monit/Caddyfile, monit/README.md
Tested with default monit configs. All seems to be working, no errors in the console. Hopefully this will help somebody.
update: I've just started to get issues with this, so if someone could test it it would be good
=> Added Monit Configuration

jupyter/Caddyfile, jupyter/Readme.md
This is a Caddyfile for Jupyter notebooks.
=> Jupyter Caddyfile

web2py/Caddyfile, web2py/README.md
https://github.com/caddyserver/examples/issues/120
=> add web2py

rails/Caddyfile, rails/README.md
I just got my rails app running on caddy in production, and this is the setup I used. The `transparent` might not even be necessary, but I'm still new to this.
=> adding example Caddyfile for a rails app setup

README.md
The link to the Caddy forum didn't resolve for me.
=> Fixed typo in link to Caddy forum
