caddyserver/examples

- django/Caddyfile
This way gunicorn (django) knows if its serving https.
> Added header for protocol

- systemd/caddy.service
I have not seen anyone put caddy at /opt/caddy/caddy, and getcaddy.com follows /usr/local/bin as well
> Change path to caddy binary

- markdown/templates/index.html
I had to change it to make it work.
Although it looks like Summarize function ignores metadata on top of markdown files, so there is some place for improvement :)
> Update Markdown example to make index working

- nextcloud/Caddyfile
- nextcloud/README.md
The config is based on [this](https://caddyserver.com/blog/caddy_and_owncloud) post from the caddy blog. I wondered why it’s missing from this examples repo so I added it with some changes like the new `status`-directive and the change to nextcloud.
> Add Nextcloud example

- kirby/Caddyfile_root
- kirby/Caddyfile_subdir
The Kirby admin panel didn't load any js, css or font files under `/panel/assets`. They were rewritten to `panel/index.php` too, so I added an exception for that. I'm not an expert, but I think everything under `/panel/assets` is only public files.
There's still the problem that going to `localhost:8080/panel` shows the error page, but going to `localhost:8080/panel/` shows the proper panel login page, so it seems that the rewrite only works when there's the trailing slash. Any idea hot to have the rewrite apply without the slash too?
> Kirby fix: allow public access to panel js, css, etc.

- grav/Caddyfile
This PR provides additional security settings also present in the [sample file](
https://github.com/getgrav/grav/blob/af53d79e5ee5f9cdc407b799a204c79897bf21d7/webserver-configs/Caddyfile) which grav provides.
But since the caddy syntax has changed since then I updated it to work.
> Improve Grav security

- seafile/Caddyfile
Updated config file to more closely match Seafile's documentation. This would close https://github.com/caddyserver/examples/issues/44
'without' trims the /seafhttp prefix from requests, like the regexp in Seafile's example nginx config: https://manual.seafile.com/deploy/https_with_nginx.html
Also included /media folder for static serving. This could alternatively be done with root and except directives in the first domain block.
gzip for good measure
> Updated Caddyfile for Seafile

- gitlab/Caddyfile
Logs automatically rotate, error log format updated to move log file outside of {} and "proxy_header" was replaced with "header_upstream"
> Update Gitlab example for Caddy v0.10

- shopware/Caddyfile
The current example does not work if you browse the shop without a path. This fix sets the index file to `shopware.php` which will then show the frontend if you simply open `https://shop.com`.
> Define shopware.php as index for fastcgi

- django/Caddyfile
proxy_header is deprecated and not supported in Caddy version 0.10.
The official Caddy documentation recommends using the shorthand transparent when dealing
with proxies.
Resolves: #68
> Update Django example for Caddy v0.10

- drupal/Drupal7-Caddyfile
- drupal/README.md
Hi Matt,
I have been trying out Caddy for some time, and I couldn't be happier. Thanks for the awesome work!
I could not find a Caddyfile for Drupal, and I could put together a working configuration file. This is not a 100% translation of the Apache `.htaccess` provided with it, but gets the work done. Some of the .htaccess directives were necessary for Caddy (for example setting explicit `Content-Encoding` headers for `gz` files). 
Please review if you have some time, and let me know if any further changes are necessary. 
Cheers!
> Drupal 7 example conf file

- gitlab/Caddyfile-socket
This example uses UNIX socket rather than TCP which could benefit performance. I am using this exact configuration on my GitLab server (described with more details here: https://blog.k0nsl.org/2017/04/29/a-note-on-gitlab-with-caddy/)
> gitlab: Use UNIX socket

- nextcloud/Caddyfile
This PR fixes it.
Without these changes filelist interface is loaded, but files list itself is missing.
> Nextcloud Caddyfile doesn't allow to use public sharing by link

- nextcloud/Caddyfile
Some of the images where not loading, so i translated with help a missing nginx `try_files` to caddy syntax.
See https://caddy.community/t/remove-index-php-from-uri-rewrite/2895
> Added rewrite for images in Nextcloud

- nextcloud/Caddyfile
While the last added public rewrite might have fixed the issue with accessing public download links, it wasn't possible for remote users to get proper download links at all.
With the rewrite before, it was possible to reach the list of files on a remote folder, but trying to download files causes a moderate flood of requests on both ends due to Nextcloud being eager to find the file that is requested.
These two rewrites fix the issue and make remote sharing work fine.
> Nextcloud: fix rewrite for remote shares

- drone/Caddyfile
You must disable gzip compression for streamed data otherwise the live updates won’t be instant
See: http://docs.drone.io/setup-with-caddy/
drone 0.8
> Changed drone Caddyfile (drone 0.8)

- discourse/README.md
Leaving that lines uncommented make Nginx try to fetch Let's Encrypt certificates, which will make the container fail as it does not have access to open ports. 
Commenting them fixes the problem.
> Updated readme to avoid Nginx error

- ghost/Caddyfile
- ghost/README.md
This is a general example to show how to use the blogging plate-form Ghost with Caddy.
The installation is pretty straightforward. We just need to ask Ghost not to use Nginx during the installation, in order to use Caddy.
> Add Ghost Caddy exemple

- nextcloud/Caddyfile
This is what finally fixed my nextcloud not syncing with the desktop client. Maybe it sometimes uses URLs with double trailing slashes?
> Fix trailing slash

- phabricator/Caddyfile
The version in the repo rewrites every single request URI as /index.php?__path__=/, this version will function properly with both the root URL on a domain and all subpages.
> Fix base rewrite for phabricator

- nextcloud/Caddyfile
Nextcloud 14 will show a warning on the Administration page if 'Referrer Policy' is not set.
Updated Caddyfile to include explicit setting for Referrer Policy to make warning go away.
Also updated Strict Transport Security to bring it in line with what Nextcloud suggests.
> Nextcloud: Update Caddyfile for Nextcloud 14

- drone/Caddyfile
Drone 1.0 is almost done, and the gzip rule:
```
...
gzip {
not /stream/
}
```
needs to be changed to:
```
...
gzip {
not /api/
}
```
Drone 1.0 is an RC1 version, so you may want to wait until it reaches the 1.0 final to merge.
> Update gzip rule on Caddyfile for Drone 1.0

- radicale/Caddyfile
- radicale/README.md
Since Radicale 2.0 we have to "remove the location from the URL path that is forwarded to Radicale" by the proxy (if not "/") [link](https://radicale.org/proxy/). 
This pull request updates the radicale example with the `without` rule that can do that if needed.
> Radicale2.0 example

- collabora/Caddyfile
- collabora/README.md
This Pull Request adds an example to use Collabora (CODE) with caddy. Collabora can then be used with, e.g., [Nextcloud](https://nextcloud.com/collaboraonline/).
> Added Collabora (CODE)

- flask/README.md
The gunicorn command was written to run a django app, a Flask app uses the MODULE_NAME:app pattern instead of something.wsgi.
See [here](http://docs.gunicorn.org/en/stable/run.html#gunicorn) for a Flask example and [here](http://docs.gunicorn.org/en/stable/run.html#gunicorn) for a django example
> Changed gunicorn command to be correct for Flask
